preset: recommended

risky: false

enabled:

disabled:
  - align_double_arrow
  - phpdoc_separation
  - concat_without_spaces

finder:
  exclude:
    - "lib"
    - "shell"
    - "views"
  name:
    - "*.php"
